# Generated by Django 4.1.6 on 2023-02-17 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_updated_at_remove_note_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteversion',
            name='version_number',
        ),
    ]
