# Generated by Django 4.1.6 on 2023-02-14 10:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_remove_note_updated_at_note_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
