# Generated by Django 4.1.6 on 2023-02-14 12:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_note_created_at_alter_note_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='archived_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
    ]
