# Generated by Django 4.1.6 on 2023-02-15 05:20

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0006_alter_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='shared_with',
            field=models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL),
        ),
    ]
