# Generated by Django 4.1.6 on 2023-02-15 08:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_alter_note_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
